### ISSUE TITLE
Re-rendering a SVG barcode fails

### ISSUE THREAD

**Issue by fragglebob** [kciter/react-barcode#5]
JsBarcode have a fix for this in their repo today, the dependency just needs updating to 3.3.18. But it set to 3.3.16 currently. Probably would be worth setting the dependency to ~3.3.18 to allow bug fixes from JsBarcode.

**Comment by kciter** [comment]
Hello, @fragglebob.
I changed JsBarcode dependency version in `package.json`. 😄

**Comment by lindell** [comment]
Great.

I still think what @fragglebob said about using `~3.3.18` (or using `3.x` or similar) instead of `3.3.18`  would be a good idea. This would mean that people installing react-barcode via npm would automatically get the JsBarcode updates without manual change in this repo.

I use [semver](http://semver.org/) versioning which is required for this to work.
