### ISSUE TITLE
Type support

### ISSUE THREAD

**Issue by dor1202** [kciter/react-barcode#66]
Is there any types support plan in the future?

**Comment by JeffreyStevens** [comment]
I had to add this to my types.d.ts to work around the issue:

declare module 'react-barcode';

**Comment by dor1202** [comment]
@JeffreyStevens Hi!
Adding the `declare module 'react-barcode';` doesn't seem to work for me, except creating a types file for the package, do you have more ideas?

**Comment by dor1202** [comment]
@JeffreyStevens .
It looks like they added types about 6 months ago in [This file](https://github.com/kciter/react-barcode/blob/master/src/react-barcode.d.ts) and based on commit [#27c](https://github.com/kciter/react-barcode/commit/27c3f62c2ba9dcfb383fbf15aca9962f83dc5c09) they added the types but the types still not downloading from npm due to missing #64 , so adding only `declare module 'react-barcode';` has no effect.
Did you add a custom file types? if so can you send it to me?

**Comment by JeffreyStevens** [comment]
Ok, I was getting this error and the declare fixes it for our Typescript project. We do have a custom type.d.ts file for our project for this purpose.

```
ERROR in src/components/BarcodeLabel.tsx:2:21
TS7016: Could not find a declaration file for module 'react-barcode'. '/Users/m087610/tfs/STS-Cloud-UI/sts-react/node_modules/react-barcode/lib/react-barcode.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-barcode` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-barcode';`
    1 | import React, {FC, MutableRefObject} from 'react';
  > 2 | import Barcode from 'react-barcode';
      |                     ^^^^^^^^^^^^^^^
```

**Comment by rtmann** [comment]
This project has types but they are done incorrectly.   The file needs to be renamed to index.d.ts instead of react-barcode.d.ts.

Literally just need to rename the react-barcode.d.ts in this project.  Typescript types resolution uses a schema like this

* node_modules/types/package-name-here/index.d.ts

So when importing Barcode from 'react-barcode' it can't find the index.d.ts.

**Comment by fnimick** [comment]
This doesn't appear to solve the issue - I'm still getting an error on 1.4.4 that the types are missing.

**Comment by fnimick** [comment]
@kciter fyi 1.4.4 doesn't resolve the issue. The problem is that the built package has a malformed types entry in `package.json` - it refers to `src/index.d.ts` which doesn't exist in the downloaded package.

I suggest moving `index.d.ts` to the top level of the built package, which solves the problem. Not sure how to do that with your build system though.
